# Generated by Django 4.2.17 on 2024-12-19 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(db_column='id клиента', primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='ФИО', max_length=255)),
                ('number', models.CharField(db_column='Номер телефона', max_length=20)),
                ('mail', models.EmailField(db_column='Почта', max_length=254)),
                ('client_adress', models.CharField(db_column='Адрес', max_length=100)),
            ],
            options={
                'db_table': '[Клиент]',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(db_column='id договора', primary_key=True, serialize=False)),
                ('monthly_fee', models.DecimalField(db_column='Ежемесячная плата', decimal_places=2, max_digits=8)),
                ('effective_date', models.DateTimeField(db_column='Срок начала действия')),
                ('expiry_date', models.DateTimeField(db_column='Срок окончания действия')),
                ('sale', models.DecimalField(db_column='Скидка', decimal_places=2, max_digits=5)),
                ('client', models.ForeignKey(db_column='Клиент', on_delete=django.db.models.deletion.CASCADE, to='contracts.client')),
            ],
            options={
                'db_table': '[Договор]',
                'ordering': ['contract_id'],
            },
        ),
    ]
